version: '3.7'

services:

  loc_preview:
    container_name: loc_preview
    image: postgres:13
    environment:
      POSTGRES_USER: "loc"
      POSTGRES_PASSWORD: "loc"
      POSTGRES_DB: "localizations"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    command: -p 5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  loc_redis_preview:
    container_name: loc_redis_preview
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_volume:
