version: '3.7'

services:

  loc_preview:
    container_name: loc_preview
    image: postgres:13
    environment:
      POSTGRES_USER: "loc"
      POSTGRES_PASSWORD: "loc"
      POSTGRES_DB: "localizations"
    ports:
      - "5435:5432"
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backend/V1.0_init.sql:/docker-entrypoint-initdb.d/V1.0_init.sql

  loc_redis_preview:
    container_name: loc_redis_preview
    image: redis
    ports:
      - "6379:6379"
    restart: always