version: '3.7'

services:

  loc_preview:
    container_name: loc_preview
    image: postgres:13
    environment:
      POSTGRES_USER: "loc"
      POSTGRES_PASSWORD: "loc"
      POSTGRES_DB: "localizations"
    expose:
      - "5435"
    ports:
      - "5435:5432"
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    command: -p 5435
    volumes:
      - db_volume:/var/lib/postgresql/data

  loc_redis_preview:
    container_name: loc_redis_preview
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_volume:
